/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBEntites.Department;
import DBEntites.Employee;
import DBEntites.Project;
import DBEntites.WorksOn;
import static GUI.MainFrame.em;
import java.awt.event.KeyEvent;
import java.util.Collection;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Girguis
 */
public class EmployeesByDepAndProject extends javax.swing.JPanel {

    /**
     * Creates new form EmployeesByDepAndProject
     */
    public EmployeesByDepAndProject() {
        initComponents();
        tableModel = (DefaultTableModel) tableOfData.getModel();
        initList();
    }

    private void initList() {
        List<Department> deps = em.createNamedQuery("Department.findAll").getResultList();
        for (Department d : deps) {
            depList.addItem(d.getDname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        depList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        proList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        workingHours = new javax.swing.JTextField();
        retrieveData = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tableOfData = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("<html>Get all employees in specific<br>dep with min working hours<br> on certian project");

        depList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depListItemStateChanged(evt);
            }
        });

        jLabel2.setText("Departments");

        jLabel3.setText("Project");

        jLabel4.setText("working hours");

        workingHours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                workingHoursKeyTyped(evt);
            }
        });

        retrieveData.setText("Retrieve");
        retrieveData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrieveDataMouseClicked(evt);
            }
        });

        tableOfData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee name", "Department", "Project", "Working hours"
            }
        ));
        jScrollPane.setViewportView(tableOfData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(workingHours, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(proList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(depList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(retrieveData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workingHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(retrieveData, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void depListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depListItemStateChanged
        Department dep = (Department) em.createNamedQuery("Department.findByDname").setParameter("dname",depList.getSelectedItem().toString()).getSingleResult();
        Collection<Project> projects = dep.getProjectCollection();
        proList.removeAllItems();
        for (Project p : projects) {
            proList.addItem(p.getPname());
        }
    }//GEN-LAST:event_depListItemStateChanged

    private void retrieveDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrieveDataMouseClicked
        if (!workingHours.getText().isEmpty()) {
            Department d = (Department) em.createNamedQuery("Department.findByDname").setParameter("dname", depList.getSelectedItem().toString()).getSingleResult();
            Collection<Employee> employees = d.getEmployeeCollection();
            String projectName = proList.getSelectedItem().toString();
            tableModel.setNumRows(0);
            double totalWorkingHours, workingHoursVal = Double.parseDouble(workingHours.getText());
            for (Employee e : employees) {
                totalWorkingHours = 0;
                Collection<WorksOn> worksOnCollection = e.getWorksOnCollection();
                for (WorksOn w : worksOnCollection) {
                    if (w.getProject().getPname().equalsIgnoreCase(projectName) && w.getHours()!=null) {
                        totalWorkingHours += w.getHours().doubleValue();
                    }
                }
                if (totalWorkingHours >= workingHoursVal) {
                    tableModel.addRow(new Object[]{e.getFullName(), d.getDname(), projectName, totalWorkingHours});
                }
            }
        }
    }//GEN-LAST:event_retrieveDataMouseClicked

    private void workingHoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workingHoursKeyTyped
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)
            evt.consume();
    }//GEN-LAST:event_workingHoursKeyTyped

    private DefaultTableModel tableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> depList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JComboBox<String> proList;
    private javax.swing.JButton retrieveData;
    private javax.swing.JTable tableOfData;
    private javax.swing.JTextField workingHours;
    // End of variables declaration//GEN-END:variables
}
